language: c

sudo: false

addons:
  postgresql: "9.4"

env:
  global:
    - LUAROCKS=3.4.0
    - LUACJSON=f8e36f8
  matrix:
    - LUA=lua5.1    LUA_32BITS=no
    - LUA=lua5.2    LUA_32BITS=no
    - LUA=lua5.3    LUA_32BITS=no
    - LUA=lua5.4    LUA_32BITS=no
    - LUA=lua5.3    LUA_32BITS=yes
    - LUA=lua5.4    LUA_32BITS=yes
    - LUA=luajit2.0 LUA_32BITS=no
    - LUA=luajit2.1 LUA_32BITS=no

before_install:
  - source .travis/setenv_lua.sh

install:
  - mkdir -p .lua-cjson
  - curl -R -L https://github.com/openresty/lua-cjson/archive/${LUACJSON}.tar.gz | tar xzf - --strip-components=1 -C .lua-cjson
  - luarocks install busted
  - luarocks install luasocket
  - luarocks install luasec
  - luarocks install moonscript
  - pushd .lua-cjson && luarocks make && popd
  - luarocks install cqueues
  - test "$LUA" = "lua5.1" && luarocks install luabitop || true
  - test "$LUA" = "lua5.2" && luarocks install luabitop || true

script:
  - luarocks make
  - busted

